/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.TeamRocket;

import org.junit.Test;
import static org.junit.Assert.*;

import edu.TeamRocket.model.Department;
import edu.TeamRocket.model.Employee;
import edu.TeamRocket.model.ExperienceLevel;
import edu.TeamRocket.model.Shift;

public class EmployeeTests {
   
    @Test

    public void TestCreateValidEmployee(){

        Employee employee = new Employee( "jesse", 6, Department.SECURITY, Shift.NIGHT, ExperienceLevel.EXPERTO);

        assertNotNull(employee);
        assertEquals(6, employee.getId() );
        assertEquals("jesse", employee.getName());
        assertEquals(Department.SECURITY, employee.getDepartment());
    }


    @Test

    public void TestCreateEnployee0(){

        assertThrows(IllegalArgumentException.class, () -> 

            new Employee("Antonio", 0, Department.SECURITY, Shift.AFTERNOON, ExperienceLevel.NOVATO)
        );
    }


    @Test

    public void TestIdNotNull(){

         Employee employee = new Employee( "jesse", 6, Department.SECURITY, Shift.MORNING, ExperienceLevel.NOVATO);
         String resultado = "Empleado [6 , jesse, SECURITY, NOVATO, MORNING]" ;

        

        assertEquals(resultado, employee.toString());
    }

}



